### ISSUE TITLE
use postgresql conn string not working

### ISSUE THREAD

**Issue by beckietech** [DHI/terracotta#340]
terracotta, version 0.8.3

config.toml:
DRIVER_PATH = "postgresql+psycopg2://postgres:[password]@localhost:5432/terracotta"
DRIVER_PROVIDER = postgresql

terracotta -c /home/bill/config.toml ingest /home/bill/optimized/{date}_forecast.tif -o /home/bill/test.sqlite
Uncaught exception!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/usr/local/lib/python3.9/dist-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/usr/local/lib/python3.9/dist-packages/toml/decoder.py", line 910, in load_value
    raise ValueError("This float doesn't have a leading "
ValueError: This float doesn't have a leading digit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/terracotta/scripts/cli.py", line 63, in entrypoint
    cli(obj={})
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1077, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1644, in parse_args
    rest = super().parse_args(ctx, args)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 2356, in process_value
    value = self.type_cast_value(ctx, value)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 2344, in type_cast_value
    return convert(value)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 2316, in convert
    return self.type(value, param=self, ctx=ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/types.py", line 83, in __call__
    return self.convert(value, param, ctx)
  File "/usr/local/lib/python3.9/dist-packages/terracotta/scripts/click_types.py", line 129, in convert
    return dict(toml.load(value))
  File "/usr/local/lib/python3.9/dist-packages/toml/decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "/usr/local/lib/python3.9/dist-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 2 column 1 char 82)

am I doing it wrong? please advise! Thank you!

**Comment by dionhaefner** [comment]
What's in your `config.toml` file? Looks like Terracotta can't parse it.

**Comment by beckietech** [comment]
As I put it in config.toml file. No more and no less, and it’s the only example I found.Best regards, Bill ShihDion Häfner ***@***.***> 於 2024年7月3日 15:57 寫道：﻿
What's in your config.toml file? Looks like Terracotta can't parse it.

**Comment by dionhaefner** [comment]
You forgot to quote `DRIVER_PROVIDER`:

```toml
DRIVER_PROVIDER = "postgresql"
```

**Comment by beckietech** [comment]
@dionhaefner, thnak you! After added quotes, it started ingesting!

However, I didn't see changes added in target database. Can you show me some example what to expect after this action?

Best regards,

**Comment by beckietech** [comment]
and also when i brwose the map, on upper right corner, it says:  Search for datasets ... and spinning. I don't know if this is correct.

**Comment by dionhaefner** [comment]
`terracotta ingest` can only ingest into SQLite databases. For advanced use cases like postgres, please use [the Python API](https://terracotta-python.readthedocs.io/en/latest/get-started.html#using-the-python-api).

**Comment by beckietech** [comment]
@dionhaefner, thank you. Since I am newbee to GIS, when I look at python code, I wonder how can I get keys from raster, for example:  KEYS = ["type", "rp", "rcp", "epoch", "gcm"] ; KEYS = ('sensor', 'tile', 'date', 'band'), is there tools / methods to describe a raster file?

**Comment by dionhaefner** [comment]
Keys are arbitrary values that identify a dataset - you are free to choose whatever you want. In your example ingest command, the only key would be `date`.
